version: "3"

services:

    app:
        build:
            context: .
        ports:
            - 8080:8080
        volumes:
            - .:/var/www/html
        networks:
            - app

    db:
        image: postgres
        ports:
            - 5432:5432
        networks:
            - app
        environment:
          POSTGRES_PASSWORD: luce
          POSTGRES_USER: luce

networks:
    app:
