<?php
/** @var ObjectivePHP\Middleware\Action\PhtmlAction\PhtmlAction $this */

$fmt = numfmt_create('fr_FR', NumberFormatter::CURRENCY);
?>
<div class="row">
    <nav class="col-sm-3 order-last">
        <h2>À propos</h2>
        <p>
            Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum.
        </p>

        <p>
            <a href="" class="lead btn btn-success">Afficher ce qui reste à offrir.</a>
        </p>

        <h2>Choisir une catégorie</h2>

        <p class="category">
        <?php foreach ($this->get('categories') as $category): ?>
            <?php if ($category == $this->get('selected_category')): ?>
                <a class="btn btn-dark" href="/">
                    <?= htmlspecialchars($category, ENT_QUOTES|ENT_SUBSTITUTE) ?>
                    <span>&times;</span>
                </a>
            <?php else: ?>
                <a class="btn btn-light" href="<?= sprintf('/?category=%s', $category) ?>">
                    <?= htmlspecialchars($category, ENT_QUOTES|ENT_SUBSTITUTE) ?>
                </a>
            <?php endif; ?>
        <?php endforeach; ?>
        </p>
    </nav>

    <main class="col-sm-9">
    <?php foreach ($this->get('list') as $category => $list): ?>
        <section class="category">
            <h2><?= htmlspecialchars($category, ENT_QUOTES|ENT_SUBSTITUTE) ?></h2>
            <div class="card-columns">
                <?php foreach ($list as $gift): ?>
                <article class="card gift<?= !empty($gift['bought_by']) ? ' offered' : '' ?>">
                    <?php if (!empty($gift['images'])): ?>
                        <a class="card-img-top" href="<?= htmlspecialchars($gift['online_shop_url'], ENT_QUOTES|ENT_SUBSTITUTE) ?>" title="Voir sur une boutique en ligne">
                            <img
                                class="image img-fluid"
                                src="/images?id=<?= htmlspecialchars($gift['images'][0]['id'], ENT_QUOTES|ENT_SUBSTITUTE) ?>"
                                width="<?= htmlspecialchars($gift['images'][0]['width'], ENT_QUOTES|ENT_SUBSTITUTE) ?>"
                                height="<?= htmlspecialchars($gift['images'][0]['height'], ENT_QUOTES|ENT_SUBSTITUTE) ?>"
                                alt="<?= htmlspecialchars($gift['images'][0]['alt'], ENT_QUOTES|ENT_SUBSTITUTE) ?>"
                            >
                        </a>
                    <?php endif; ?>
                    <div class="card-body">
                        <h3><?= htmlspecialchars($gift['what'], ENT_QUOTES|ENT_SUBSTITUTE) ?></h3>

                        <p class="description card-text">
                            <?= htmlspecialchars($gift['description'], ENT_QUOTES|ENT_SUBSTITUTE) ?>
                        </p>
                        <a class="url card-link" href="<?= htmlspecialchars($gift['online_shop_url'], ENT_QUOTES|ENT_SUBSTITUTE) ?>">Voir sur une boutique</a>
                    </div>
                    <footer class="card-footer lead clearfix">
                        <?php if (empty($gift['bought_by'])): ?>
                            <span class="align-middle">
                                Environ <?= numfmt_format_currency($fmt, htmlspecialchars($gift['observed_price'], ENT_QUOTES|ENT_SUBSTITUTE), 'EUR') ?>
                            </span>
                            <button class="btn btn-primary float-right align-top" type="button" data-toggle="modal" data-target="#give-modal">Offrir</button>
                        <?php else: ?>
                            Offert par <em><?= htmlspecialchars($gift['bought_by'], ENT_QUOTES|ENT_SUBSTITUTE) ?></em>
                        <?php endif; ?>
                    </footer>
                </article>
                <?php endforeach; ?>
            </div>
        </section>
    <?php endforeach; ?>
        <div class="modal fade" id="give-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Offrir</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form>
                            <div class="form-group">
                                <label for="whom">Votre nom&nbsp:</label>
                                <input type="text" class="form-control" id="whom" name="whom">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                        <button type="button" class="btn btn-primary" id="give">Offrir</button>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
<script src="/dist/build.js"></script>
<script>
(function ($) {
    const give = $('#give');

    give.click(function (event) {
        const whom = $('#whom');

        console.log(whom.val());
        if (whom.val().trim() !== '') {
            alert(whom.val());
        }
    });
})(window.jQuery);
</script>
