<?php

/** @var ObjectivePHP\Middleware\Action\PhtmlAction\PhtmlAction $this */

use Luce\Service\BirthListManager;

$fmt = numfmt_create('fr_FR', NumberFormatter::CURRENCY);

$query = [];
$query['category'] = $this->get('selected_category') ?? null;
$query['offered'] = $this->get('offered') !== BirthListManager::SHOW_ALL ? $this->get('offered') : null;

function build_query_string(array $base, array $query)
{
    $query = http_build_query(array_merge($base, $query));

    return empty($query) ? '/' : '/?' . $query;
}
?>
<div class="row">
    <nav class="col-md-3 order-last">
        <h2>À propos</h2>
        <p>
            Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum.
        </p>

        <p>
            <?php if ($this->get('offered') == BirthListManager::SHOW_ALL) : ?>
                <a href="<?= build_query_string($query, ['offered' => 0]) ?>" class="lead btn btn-success">Afficher ce qui reste à offrir</a>
            <?php else : ?>
                <a href="<?= build_query_string($query, ['offered' => null]) ?>" class="lead btn btn-success">Touts afficher</a>
            <?php endif; ?>
        </p>

        <h2>Choisir une catégorie</h2>

        <p class="category">
        <?php foreach ($this->get('categories') as $category) : ?>
            <?php if ($category == $this->get('selected_category')) : ?>
                <a class="btn btn-dark mb-1" href="<?= build_query_string($query, ['category' => null]) ?>">
                    <?= htmlspecialchars($category, ENT_QUOTES|ENT_SUBSTITUTE) ?>
                    <span>&times;</span>
                </a>
            <?php else : ?>
                <a class="btn btn-light mb-1" href="<?= build_query_string($query, ['category' => $category]) ?>">
                    <?= htmlspecialchars($category, ENT_QUOTES|ENT_SUBSTITUTE) ?>
                </a>
            <?php endif; ?>
        <?php endforeach; ?>
        </p>
    </nav>

    <main class="col-md-9">
    <?php if (!$this->get('list')) : ?>
        <div class="alert alert-primary" role="alert">
            <h2 class="alert-heading">Il n'y a plus rien à voir ici...</h2>
            <p>Ce que vous cherchez n'existe plus.</p>
            <hr>
            <a href="/" class="alert-link">Retourner à la page d'acceuil</a>
        </div>
    <?php endif; ?>
    <?php foreach ($this->get('list') as $category => $list) : ?>
        <section class="category">
            <h2><?= htmlspecialchars($category, ENT_QUOTES|ENT_SUBSTITUTE) ?></h2>
            <div class="card-columns">
                <?php foreach ($list as $gift) : ?>
                <article class="card gift<?= !empty($gift['bought_by']) ? ' offered' : '' ?>" id="gift-<?= htmlspecialchars($gift['id'], ENT_QUOTES|ENT_SUBSTITUTE) ?>">
                    <?php if (!empty($gift['images'])) : ?>
                        <a class="card-img-top" href="<?= htmlspecialchars($gift['online_shop_url'], ENT_QUOTES|ENT_SUBSTITUTE) ?>" title="Voir sur une boutique en ligne">
                            <img
                                class="image img-fluid"
                                src="/images?id=<?= htmlspecialchars($gift['images'][0]['id'], ENT_QUOTES|ENT_SUBSTITUTE) ?>"
                                width="<?= htmlspecialchars($gift['images'][0]['width'], ENT_QUOTES|ENT_SUBSTITUTE) ?>"
                                height="<?= htmlspecialchars($gift['images'][0]['height'], ENT_QUOTES|ENT_SUBSTITUTE) ?>"
                                alt="<?= htmlspecialchars($gift['images'][0]['alt'], ENT_QUOTES|ENT_SUBSTITUTE) ?>"
                            >
                        </a>
                    <?php endif; ?>
                    <div class="card-body">
                        <h3><?= htmlspecialchars($gift['what'], ENT_QUOTES|ENT_SUBSTITUTE) ?></h3>

                        <p class="description card-text">
                            <?= htmlspecialchars($gift['description'], ENT_QUOTES|ENT_SUBSTITUTE) ?>
                        </p>
                        <a class="url card-link" href="<?= htmlspecialchars($gift['online_shop_url'], ENT_QUOTES|ENT_SUBSTITUTE) ?>">Voir sur une boutique</a>
                    </div>
                    <footer class="card-footer lead clearfix">
                        <?php if (empty($gift['bought_by'])) : ?>
                            <span class="align-middle">
                                Environ <?= numfmt_format_currency($fmt, htmlspecialchars($gift['observed_price'], ENT_QUOTES|ENT_SUBSTITUTE), 'EUR') ?>
                            </span>
                            <button class="btn btn-primary float-right align-top" type="button" data-toggle="modal" data-target="#give-modal" data-what="<?= htmlspecialchars($gift['what'], ENT_QUOTES|ENT_SUBSTITUTE) ?>" data-what-id="<?= htmlspecialchars($gift['id'], ENT_QUOTES|ENT_SUBSTITUTE) ?>">Offrir</button>
                        <?php elseif ($gift['is_buyer_anonymous']) : ?>
                            Offert
                        <?php else : ?>
                            Offert par <em><?= htmlspecialchars($gift['bought_by'], ENT_QUOTES|ENT_SUBSTITUTE) ?></em>
                        <?php endif; ?>
                    </footer>
                </article>
                <?php endforeach; ?>
            </div>
        </section>
    <?php endforeach; ?>
        <div class="modal fade" id="give-modal" tabindex="-1" role="dialog" aria-labelledby="giveModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Offrir</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div id="give-alert" class="alert alert-danger d-none"></div>
                        <form id="give-form">
                            <div class="form-group">
                                <label for="whom">Votre nom&nbsp:</label>
                                <input type="text" class="form-control" id="whom" name="whom" required>
                                <div class="invalid-feedback">
                                    Veuillez donner votre nom.
                                </div>
                            </div>
                            <div class="form-group form-check">
                                <input type="checkbox" class="form-check-input" id="anonymous" name="anonymous" value="">
                                <label class="form-check-label" for="anonymous">Ne pas afficher mon nom</label>
                            </div>
                        </form>
                        <input name="what-id" id="what-id" type="hidden" value="">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                        <button type="button" class="btn btn-primary" id="give">Offrir</button>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
<script src="/dist/build.js"></script>
<script>
(function ($) {
    const
        giveModal = $('#give-modal'),
        give = $('#give'),
        whom = $('#whom'),
        whatId = $('#what-id'),
        anonymous = $('#anonymous'),
        giveAlert = $('#give-alert');

    giveModal.on('show.bs.modal', function (event) {
        const
            button = $(event.relatedTarget),
            recipient = button.data('what'),
            modal = $(this);

        whatId.val(button.data('what-id'));
        modal.find('.modal-title').html('Offrir <em>' + recipient + '</em>');
    });

    giveModal.on('shown.bs.modal', function () {
        document.getElementById('whom').focus();
    });

    giveModal.on('hide.bs.modal', function (e) {
        const form = document.getElementById('give-form');

        whom.prop("disabled", false);
        anonymous.prop("disabled", false);

        form.reset();
        whom.removeClass('is-invalid');
        giveAlert.addClass('d-none');
        giveAlert.text('');
    });

    $('#give-modal form').on('keypress', function(e) {
        const keyCode = e.keyCode || e.which;
        if (keyCode === 13) {
            e.preventDefault();
            give.click();

            return false;
        }
    });

    give.on('click', function (event) {
        const form = document.getElementById('give-form');

        if (form.checkValidity() === false) {
            whom.addClass('is-invalid');
            event.preventDefault();
            event.stopPropagation();
        } else {
            whom.removeClass('is-invalid');
            const gift = $('#gift-' + whatId.val());

            whom.prop("disabled", true);
            anonymous.prop("disabled", true);

            $.post(
                "/give",
                {'what': whatId.val(), 'whom': whom.val(), 'anonymous': $('#anonymous').is(':checked') ? 1 : 0}
            )
            .done(function() {
                gift.addClass('offered');

                if (! $('#anonymous').is(':checked')) {
                    gift.children('footer').html('Offert par <em>' + whom.val() + '</em>');
                } else {
                    gift.children('footer').html('Offert');
                }

                giveAlert
                    .removeClass('alert-danger')
                    .addClass('alert-success')
                    .text('Merci beaucoup !')
                    .removeClass('d-none');

                setTimeout(function() {
                    giveModal.modal('hide');
                    giveAlert
                        .removeClass('alert-success')
                        .addClass('alert-danger');
                }, 1500);
            })
            .fail(function(data) {
                if (data.responseJSON !== undefined) {
                    giveAlert.text(data.responseJSON.error);
                } else {
                    giveAlert.text('Oups une erreur est survenue...');
                }

                giveAlert.removeClass('d-none');
            });
        }
    });
})(window.jQuery);
</script>
