<?php
use ObjectivePHP\Application\Config\ApplicationName;
?>
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="/dist/main.css">
        <link rel="stylesheet" href="/dist/style.css">

        <title><?= $this->param(ApplicationName::KEY) ?></title>
    </head>
    <body>
        <main class="site container-fluid">
            <div class="site-content">
                <?= $this->getViewOutput(); ?>
            </div>

            <footer class="border-top">
                <p>Propulsé à l'aide de logiciels libres et un peu d'huile de coude. <span class="lead">👨‍👩‍👧</span></p>
            </footer>
        </main>
    </body>
</html>

