<?php
use ObjectivePHP\Application\Config\ApplicationName;
use ObjectivePHP\Application\Session\Session;

$session = new Session();
?>
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="/dist/main.css">
        <link rel="stylesheet" href="/dist/style.css">

        <link rel="icon" type="image/png" href="/favicon.png">

        <title><?= $this->param(ApplicationName::KEY) ?></title>
    </head>
    <body>
        <main class="site container-fluid">
            <div class="site-content">
                <?= $this->getViewOutput(); ?>
            </div>

            <footer class="border-top">
                <p>Propulsé à l'aide de logiciels libres et un peu d'huile de coude. <span class="lead">👨‍👩‍👧</span></p>
                <?php if ($session->get('password')) : ?>
                    <address>
                        🏡&nbsp;Famille Simonin, 11 rue Montplaisir - Appartement 31 - 57070 Metz
                        <span class="ml-2">☎️&nbsp;<a href="tel:+33661930156">+33&nbsp;6&nbsp;61&nbsp;93&nbsp;01&nbsp;56</a></span>
                        <span class="ml-2">✉️&nbsp;<a href="mailto:famille@simonin.name">famille@simonin.name</a></span>
                    </address>
                <?php endif; ?>
            </footer>
        </main>
    </body>
</html>
